version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "4833:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Aa@123456
      MYSQL_DATABASE: db_xx
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: Aa@123456
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
